/**
 * 🎬 YouTube 提取测试脚本
 * 
 * 测试从 YouTube 页面提取 ytInitialPlayerResponse 和字幕
 */

const { chromium } = require('playwright');

async function testYouTubeExtraction() {
  console.log('🎬 Starting YouTube extraction test...\n');
  
  const browser = await chromium.launch({
    headless: true, // 无头模式
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-blink-features=AutomationControlled'
    ]
  });
  
  const context = await browser.newContext({
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36',
    viewport: { width: 1920, height: 1080 },
    ignoreHTTPSErrors: true
  });
  
  const page = await context.newPage();
  
  try {
    const videoUrl = 'https://www.youtube.com/watch?v=y2NeAef6d30';
    console.log(`📺 Loading: ${videoUrl}\n`);
    
    await page.goto(videoUrl, {
      waitUntil: 'domcontentloaded',
      timeout: 30000
    });
    
    // 等待页面加载
    await page.waitForTimeout(5000);
    
    console.log('✅ Page loaded, extracting data...\n');
    
    // 提取 ytInitialPlayerResponse
    const result = await page.evaluate(async () => {
      const pr = window.ytInitialPlayerResponse;
      if (!pr) {
        return { error: 'ytInitialPlayerResponse not found' };
      }
      
      const vd = pr.videoDetails || {};
      const mf = pr.microformat?.playerMicroformatRenderer || {};
      
      // 基本元数据
      const metadata = {
        title: vd.title,
        author: vd.author,
        channelId: vd.channelId,
        videoId: vd.videoId,
        lengthSeconds: vd.lengthSeconds,
        viewCount: vd.viewCount,
        publishDate: mf.publishDate || mf.uploadDate,
        ownerChannelName: mf.ownerChannelName,
        description: vd.shortDescription?.substring(0, 200) + '...'
      };
      
      // 检查字幕
      const captions = pr.captions?.playerCaptionsTracklistRenderer;
      const captionInfo = {
        hasCaptions: !!captions,
        tracksCount: captions?.captionTracks?.length || 0,
        tracks: []
      };
      
      if (captions?.captionTracks) {
        captionInfo.tracks = captions.captionTracks.map(t => ({
          languageCode: t.languageCode,
          kind: t.kind || 'manual',
          name: t.name?.simpleText || t.name?.runs?.[0]?.text,
          baseUrl: t.baseUrl?.substring(0, 100) + '...' // 只显示前100字符
        }));
        
        // 尝试获取第一个字幕轨道的内容
        if (captions.captionTracks.length > 0) {
          const track = captions.captionTracks[0];
          const transcriptUrl = track.baseUrl + '&fmt=json3';
          
          try {
            console.log('Fetching transcript from:', transcriptUrl.substring(0, 100));
            const res = await fetch(transcriptUrl);
            const data = await res.json();
            
            // 解析字幕文本
            let text = '';
            for (const event of (data.events || [])) {
              for (const seg of (event.segs || [])) {
                if (seg.utf8) text += seg.utf8;
              }
            }
            
            captionInfo.transcript = {
              language: track.languageCode,
              isAutoGenerated: track.kind === 'asr',
              textLength: text.length,
              preview: text.substring(0, 200) + '...'
            };
          } catch (e) {
            captionInfo.transcript = {
              error: e.message
            };
          }
        }
      }
      
      return {
        success: true,
        metadata,
        captions: captionInfo
      };
    });
    
    console.log('📊 Extraction Result:\n');
    console.log(JSON.stringify(result, null, 2));
    
    if (result.success && result.captions.transcript) {
      console.log('\n✅ Successfully extracted transcript!');
      console.log(`   Language: ${result.captions.transcript.language}`);
      console.log(`   Auto-generated: ${result.captions.transcript.isAutoGenerated}`);
      console.log(`   Text length: ${result.captions.transcript.textLength} chars`);
    } else if (result.captions.hasCaptions) {
      console.log('\n⚠️  Captions available but transcript fetch failed');
      console.log(`   Error: ${result.captions.transcript?.error || 'Unknown'}`);
    } else {
      console.log('\n❌ No captions available for this video');
    }
    
  } catch (error) {
    console.error('\n❌ Error:', error.message);
  } finally {
    await browser.close();
  }
}

testYouTubeExtraction().catch(console.error);
